import test from 'node:test'
import assert from 'node:assert/strict'
import { writeFile, mkdir } from 'node:fs/promises'
import { batchDataSchema, newScript, newScene, missingScript, emptyProfile, type Batch } from './model'
import { publicAddress, readWebsite } from './web-source'
import { createWord } from './word'
const script={...newScript('ads'),title:'Una idea de prueba',objective:'Consultas',idea:'Un ejemplo',insight:'Un deseo',angle:'Una mirada',format:'Habla a cámara',hookSpoken:'Una pregunta',hookVisual:'Plano detalle',proof:'Demostración del producto',payoff:'La respuesta',cta:'Visita la página',requirements:'Talento, producto, locación',brandReviewed:true,scenes:[{...newScene('Gancho'),visual:'Manos mostrando producto',audio:'Una pregunta'},{...newScene('CTA'),visual:'Persona a cámara',audio:'Visita la página'}],status:'listo' as const}
const data={objective:'Ejemplo',platform:'Instagram',ads:1,organic:0,scripts:[script]}
test('Un guion revisado requiere contenido y revisión, no forzar polémica',()=>{assert.deepEqual(missingScript(script),[]);assert.equal(script.checks.some(Boolean),false);assert.ok(batchDataSchema.safeParse(data).success);assert.ok(!batchDataSchema.safeParse({...data,scripts:[{...script,brandReviewed:false}]}).success)})
test('La tanda limita cantidad, tipo, IDs duplicados y tamaño',()=>{assert.ok(!batchDataSchema.safeParse({...data,ads:0,organic:1}).success);assert.ok(!batchDataSchema.safeParse({...data,ads:2,scripts:[script,script]}).success);assert.ok(!batchDataSchema.safeParse({...data,ads:31}).success);assert.ok(!batchDataSchema.safeParse({...data,scripts:[{...script,title:'a'.repeat(200)}]}).success)})
test('El lector de fuentes rechaza redes internas IPv4/IPv6 y URLs inseguras',async()=>{for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.1.1','::1','::ffff:127.0.0.1','fc00::1'])assert.equal(publicAddress(ip),false,ip);assert.ok(publicAddress('8.8.8.8'));for(const url of ['http://example.com','https://user:pass@example.com','https://127.0.0.1','https://[::1]'])await assert.rejects(readWebsite(url))})
test('El Word es un DOCX y contiene escenas, estrategia y requerimientos',async()=>{const b:Batch={id:crypto.randomUUID(),marca_id:crypto.randomUUID(),name:'Tanda de prueba',recording_id:null,data,revision:1,updated_at:new Date().toISOString()};const buffer=await createWord(b,'Marca de prueba',{...emptyProfile,positioning:'Posicionamiento de prueba'});assert.equal(buffer.subarray(0,2).toString(),'PK');assert.ok(buffer.length>7000);await mkdir('/tmp/distinto-studio-test',{recursive:true});await writeFile('/tmp/distinto-studio-test/guiones.docx',buffer)})
